### ISSUE TITLE
Trace history of particles?

### ISSUE THREAD

**Issue by sdwfrost** [tgvaughan/MASTER#45]
I'm interested in using MASTER to simulate epidemic models where I can reconstruct 'who infected whom'. Is there a way to uniquely label particles (or whatever you'd like to call individuals here) and keep track of the complete event history?

**Comment by tgvaughan** [comment]
Hey Simon, this is essentially equivalent to keeping the entire transmission tree, am I right?  In which case yes, it's possible to do this, but it uses loads of memory as it's only written to disk (as a gigantic annotated Newick file) once the simulation is complete.

**Comment by sdwfrost** [comment]
I am looking at fairly small population sizes, and can keep the transmission tree size down quite easily (e..g an SI model with a fixed population size).

**Comment by tgvaughan** [comment]
In this case then it's easy: just use LineageSeed or LineageSeedMultiple to construct the initial condition (these produce individuals whose history will be recorded in the tree) and write the result to disk using NexusOutput.  This will produce a tree containing every event in the epidemic.

**Comment by sdwfrost** [comment]
Whilst this may contain every event, I can't trace who-infected-whom though unless there's some way of uniquely labelling each individual?

**Comment by tgvaughan** [comment]
The order of individuals in reaction products should map to the order siblings appear in the tree, so for instance I -> I + E should produce a node (I,E)I in the resulting newick, meaning you can identify the first child as the infector and the second as the infectee.
