### ISSUE TITLE
Query about specifying conditionals in Predicate element

### ISSUE THREAD

**Issue by jnarag** [tgvaughan/MASTER#49]
Hi Tim, 

I am trying to set up a metapopulation model in MASTER but I am not sure if I understand the predicate element correctly. In my model patches (or populations) are colonised only if the total population size is zero (i.e. only empty patches). Currently in my xml file I have specified this colonisation reaction as follows:

```
            <reaction spec='Reaction' reactionName='Colonization' rate="0.1">
                <predicate spec='Predicate'>
                	<![CDATA[
 // Colonize only if X[j] is empty and X[i] is nonzero
                		sum(j) == 0 && i != j && sum(i) > 0 
                	]]>
                </predicate>
                X[i] -> X[j]
            </reaction>

```

So my question is if I want to ensure X[j] is empty do I simply use sum(j) == 0 or have I misunderstood something? In my model, there a number of X populations corresponding to different patches. 

Thanks in advance!

**Comment by tgvaughan** [comment]
Hi @jnarag, it sounds like you're trying to have the presence/absence of a reaction depend on the state of the system.  Is that right? If this is the case you can't do this with MASTER.  The set of reactions is fixed.  The predicate element is merely there to help decide which reactions are present in the system, and these are tested only as the model is being built.  Also, the sum() function simply computes the sum of the elements of the array you pass to it: it doesn't have anything to do with the population size.

I'm sure that most of your confusion comes from the lack of good documentation around these aspects of MASTER. Sorry about that!  But just remember that MASTER only solves systems describable by a chemical master equation as defined on the first page of the wiki documentation.

Hope this helps!

**Comment by jnarag** [comment]
Thanks for the clarification about the sum() function. 

I don't think I am trying to have the presence/absence of a reaction depend on the system but perhaps I haven't properly considered the reactions correctly. Anyway, I will have to think some more whether or not MASTER is helpful for my problem.
