### ISSUE TITLE
Possible typo in message

### ISSUE THREAD

**Issue by aezarebski** [tgvaughan/MASTER#51]
Possible typo in message

https://github.com/tgvaughan/MASTER/blob/f32fb4d121296a2abb80688d90ea17b9239eb553/src/master/model/Reaction.java#L157
https://github.com/tgvaughan/MASTER/blob/f32fb4d121296a2abb80688d90ea17b9239eb553/src/master/model/PopulationSize.java#L291
https://github.com/tgvaughan/MASTER/blob/f32fb4d121296a2abb80688d90ea17b9239eb553/src/master/utilities/pfe/PFEVisitor.java#L79

**Comment by tgvaughan** [comment]
Thanks Alex.  (BTW I love how you give me the benefit of the doubt here - like "Uknown" might have some obscure technical meaning. :)  )

**Comment by aezarebski** [comment]
Naming stuff is difficult, it wouldn't surprise me in the slightest.
